# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: 이준현 (Lee Jun Hyun)
title: Senior Network System Administrator
email: brett.h@email.co.uk
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: facespics
github_username: sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

more_content: | # this will include new lines to allow paragraphs
  ![image](images/profile.jpg)
  [끊임없이 발전하겠습니다.]

  1. 개발자로서의 성장 과정.
  [" 남들보다 꾸준히 하려고 하자 "]
  어릴 적부터 개발자라는 직업에 막연한 관심이 있었지만, 본격적으로 개발자라는 꿈을 꾼 건 2017년 겨울부터 였습니다. 2015년도에는 이천에 있는 전문대학의 보안 전공을 했습니다. 당시 학교의 커리큘럼이 네트워크와 서버를 중심으로 이루어졌기 때문에 따로 개발에 관해 공부하기 위해 C언어를 공부하기 시작했습니다. 군대를 산업체로 갔기 때문에 재직자 교육 과정으로 C언어를 공부하며 점점 개발자에 대한 꿈이 생겨나기 시작했습니다.
  그 뒤 언제나 쉽게 접하게 되는 웹사이트에 관한 관심이 생겼고, 우리의 삶 깊숙이 자리 잡고 있는 웹을 만들어보고 싶다는 생각이 들었습니다. 많은 사람이 내가 만든 웹사이트를 이용하면 어떨지, 내가 개발한 웹사이트를 다른 사람이 만족하며 잘 사용하고 있으면 어떨지에 대한 상상을 하며 웹 개발자에 대한 동경이 생겼습니다. 개발에 대해 더 공부해보고자 다니고 있던 학교를 나오고 안산대학교 인터넷 정보과에 2018년도 1학년으로 진학하게 되었습니다.
  산업체를 복무하며 html, CSS에 대한 기초적인 문법을 가르쳐 주는 단과 과정을 수강하고 전역 후에는 학교에 다니며 틈틈이 Java를 독학했습니다. 하지만 뜻대로 공부의 방향이 잡히지 않았고, 내가 작성하는 코드가 맞는 건지, 받아들이는 방식에는 문제가 없는지에 대한 고민이 생기며 학원에 다니기로 결정했습니다. 그렇게 해서 저는 학원을 병행하며 학교생활을 보내게 되었습니다.
  학원에 다니며 전자정부 프레임워크에 대해 공부하며, 단순히 페이지를 화면에 띄우는 대도 MVC 패턴을 연결해 db에서 데이터들을 SELECT하고 JSTL로 그려주는 과정이 필요하다는 걸 알게 되었습니다. 평소에는 거들떠보지도 않던 개발자 도구 화면인데 어느 순간 버릇처럼 켜 HTML 구조를 보는 신기한 경험을 했습니다.
  항상 남들보다 잘하려 하는 것도 중요하지만, 남들보다 꾸준히 하자는 마음으로 공부에 임하고 있습니다. 때로는 편안한 삶을 추구하며 현재의 생활, 현재의 모습에 만족하고 싶지만, 개발자로서 가장 중요한 자세는 편안함을 멀리해야 하는 것이라 생각합니다. 발전이 없으면 편할지 모르지만 힘든 만큼 돌아오리라 믿고 최선을 다해 공부하고 있습니다.

  [" 풀스택 개발자 "]
  제가 목표로 하는 개발자는 생각을 개발로 옮길 수 있는 개발자 입니다. 무엇이든 개발하기 위해 가장 중요한 역량은 학습 방법이라 생각합니다. 제가 개발자로써 가장 중요하게 생각하는 역량은 학습 방법이라 생각합니다. 학습 방법에 대해 끈임없이 고민하고 여러 사람들을 만나 다양한 경험을 쌓으려고 노력하고 있습니다.
  프론트엔드, 백엔드를 구분짓지는 않지만 저는 백엔드를 좀 더 깊게 공부하고 싶습니다.
  개발을 할때 클라이언트 서버에서 온 요청을 백엔드에서 처리하는 과정에서 큰 흥미를 느꼈습니다. 간단한 예로 화면에서 입력한 사용자의 비밀번호와 아이디를 서버에서 DB를 이용해 조회하고 로그인 처리를 하는 과정이 화면에 기능을 추가하는 것 보다 더 성취감이 높았습니다.
  앞으로 규모가 큰 서비스에서도 무리없이 잘 동작하는 백엔드를 개발하고 싶습니다. 이를 바탕으로 실력있는 풀스택 개발자로 성장하고 싶습니다.

  2. 성격의 장/ 단점.
  [" 한 가지 일을 해도 계획적으로 "]
  저는 학교생활과 학원을 병행하면서 정해진 계획에 맞춰 움직였습니다. 저는 항상 제가 계획해 놓은 시간 안에서 움직였습니다.
  저는 하루를 온전히 공부에 투자함에 있어서도 아침, 점심, 저녁으로 시간을 나누고 계획합니다. 단순히 학원 과제에 시간을 투자하는 게 아니라 학원 과제에서 시간이 오래 걸리는 것, 비교적 짧게 걸리는 것 혹은 가능한 한 빨리 끝내야 하는 일인지, 천천히 시간을 투자해도 되는 것인지를 나눠 그것에 맞게 스스로 기간을 정해두고 하나하나 해결해 나갔습니다. 이 점은 일을 수행하는 데 있어 정해진 틀을 만들어 놓음으로 효율적으로 시간을 관리할 수 있게 만들어주었습니다. 항상 적절한 시간을 정해두고 그 시간 안에 출발하는 습관 덕분에 특별한 일이 생기지 않는 이상 지각은 하지 않게 되었습니다.
  회사 역시 큰 틀이 정해져 있기 때문에 무리 없이 적응하여 회사에서 정해진 큰 틀을 효율적으로 활용할 것입니다.

  [" 포기하지 않는 집요함 "]
  항상 집요하게 파고들어 결국은 해냅니다. 저는 맡은 일을 집요하게 파고들며, 필요한 것이나 중요하다고 생각하는 것은 힘들고 귀찮아도 포기하지 않습니다. 한번 끝을 보겠다고 마음을 먹는다면 꼭 끝을 보는 성격입니다.
  학원 과제 중 JQuery로 학원에서 제공 받은 DOM문서에 타겟을 잡아 each문을 돌려보는 숙제를 서로 다른 예로 응용을 해본 적이 있습니다. 35번을 진행하면서 DOM문서의 대부분을 타겟으로 잡아본 기억이 있습니다. 35번 응용해보자는 마음을 먹었고 35번을 결국 해냈습니다. 처음 JQuery로 타겟을 잡을 때는 자신이 없고 어렵기만 했습니다. 하지만 개발자 도구 화면으로 DOM문서를 보며 끈질기게 타겟을 잡았습니다. 물론 타겟이 한 번에 잘 잡히지 않았지만 그럴수록 더욱 집요하게 파고들었습니다. 그 과제를 진행하면서 JQuery로 타겟을 잡는 것에 있어서 두려움을 떨쳐낼 수 있었습니다.
  이러한 장점이 업무를 진행될 때 좋은 효과를 불러올 것으로 생각합니다. 저는 난관에 부딪히더라도 포기하지 않을 것입니다.

  [" 걱정이많다 "]
  줄곧 쓸데없는 걱정이 많다는 소리를 듣습니다. 하나를 하더라도 끊임없이 고민하고 걱정합니다. 예를 들어 이벤트를 응모했을 때 떨어지면 어떡하지? 라는 생각을 자주 하곤 하며 어딘가에 놀러 갈 때도 사람이 많으면 어떡하지, 생각보다 별로면 어떡하지라는 고민을 자주 합니다. 이러하듯 막상 부딪혀보면 알 수 있는 부분들에 대한 걱정을 할 때가 있습니다. 때로는 걱정을 해봐야 소용없는 일들을 깊이 생각하기 때문에 답답해 보이기도 합니다.
  하지만 가끔은 이러한 단점이 장점으로 바뀌어 실패해도 다시 일어설 수 있는 계획을 세워주기도 합니다.
  한 가지 일을 함에서도 수십 번의 고민을 하는 단점이 때로는 돌발 상황, 위기 상황에서 마음의 준비를 할 수 있게 해줍니다. 또한 버릇처럼 고민과 걱정을 하는 성격 탓에 매번 새로운 것을 계획하고 앞으로 나아갈 수 있게 해줍니다.
  현재는 쓸데없는 걱정을 많이 하는 단점을 고치기 위해 걱정이 필요한 일과 부딪혀봐야 하는 일에 대해 생각하고 적절히 계획을 세우려 노력하고 있습니다.

  3. 공부하며 기억에 남았던 점
  [" 집요함으로 답을 얻다 "]
  학원 과제 중 Ajax 통신에서 전달하는 Object 형식의 data를 Object로 다시 한 번 더 감싸서 보낸 적이 있었습니다.
  예를 들면 {Obj : {name : 이준현}} 이런 식으로 Obj라는 키에 Object를 넣어서 전달하는 방식이었습니다. Controller에서 JsonUtil을 사용해 값을 빼내야 하는데 쉽게 데이터가 변환되지 않았습니다. 파라미터로 넘겨온 값을 JsonToMap메서드를 이용해 Map에 담아도 내부의 값은 Object 형식의 모양을 한 문자열이었기 때문에 뜻대로 되지 않았습니다. 이 문제에 대해서는 인터넷에 검색해도 잘 나오지 않았습니다. 하지만 저는 포기하지 않고 계속 파고들었습니다. 온종일 고민하고, 떠오른 아이디어를 시험해보고 실패하기를 반복했습니다. 그렇게 일주일이 넘는 시간이 흘러 문득 떠오른 생각을 구현했고, 결국 전달한 data를 파싱하는데 성공했습니다. 처음 화면에서 넘어온 Object 형식의 데이터를 JsonToMap메서드를 이용해 Map에 담고, Map에 담긴 값을 JsonToList메서드로 List에 파싱하는 걸 성공했습니다. 일주일을 넘게 일어나서 밤에 잠들기 직전까지 고민하고 실험했던 그 집요함으로 답을 얻을 수 있었습니다. 만약 기간이 더 오래 걸렸더라도 포기하지 않고 답을 찾았을 것입니다. 이 과제를 진행하면서 난관에 부딪혔을 때에 대한 자신감을 가질 수 있었습니다. 아무리 어려워도 결국은 해결할 수 있는 문제들이라 생각하고 포기하지 않고 다른 관점에서 시도해보고 도전하는 방법을 배웠습니다.

  4. 입사 포부.
  [" 신입의 자세로 "]
  신입이 갖춰야 할 자세는 항상 배우려는 자세와 적극성이라고 생각합니다. 맡은 업무에 최선을 다하고 매사에 긍정적으로 임하겠습니다. 선배님들의 말씀을 귀 기울여 듣고 잘 받아들일 수 있게 노력하겠습니다.
  커뮤니케이션은 사원과 사원을 넘어 기업과 고객의 관계에서도 아주 중요한 요소라고 생각합니다. 개발자는 기본적인 실력도 중요하지만, 의사소통 역시 굉장히 중요하다고 생각합니다. 아집을 부리지 않고 조직에 잘 녹아나는 사람이 되겠습니다.
  열정, 끈기, 실력 3박자를 골고루 갖춘 신입이 되겠습니다.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
